### ISSUE TITLE
cannot inflate FKPlayerview in playerfragment

### ISSUE THREAD

**Issue by kajaketi** [Firekast-io/firekast-demo-android#1]

**Comment by francoisrouault** [comment]
Hi! We have updated the Firekast Android SDK to version 1.2.0 that should fixed your issue. Otherwise please give us more details about your configuration (device, android version) and logs.

Here is how to implement Firekast SDK 1.2.0. Note that the dependency to ExoPlayer is no more needed.
```
implementation ('io.firekast:firekast:1.2.0') {
     exclude module: 'support-v7'
     exclude module: 'support-v13'
}
// implementation 'com.google.android.exoplayer:exoplayer:X.X.X' <<<--- Remove this line
```
