### ISSUE TITLE
FkCamera is returning null.

### ISSUE THREAD

**Issue by Shani618** [Firekast-io/firekast-demo-android#5]
Access denied finding property "camera.hal1.packagelist"

E/StreamerFradment: Request 'CreateStream [body: {"width":720,"height":1280}, query: null]' failed with exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.firekast.a.b' on a null object reference

**Comment by francoisrouault** [comment]
Hi @Shani618,
Thank you for the feedback! Can you tell me on which phone do you run the application (and it's android OS version please) ?
Regards

**Comment by Shani618** [comment]
I am using Oneplus 3T with Android Oreo API 28

**Comment by mmh4you** [comment]
i got Error Status code 401

**Comment by Yesha052** [comment]
Getting this error. Did you find solutions?
E/StreamerFradment: Request 'CreateStream [body: {"width":720,"height":1280}, query: null]' failed with exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.firekast.a.b' on a null object reference

**Comment by Shani618** [comment]
@Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        Firekast.initialize(getContext(), "YOUR_KEY");

        FKCameraFragment cameraFragment = new FKCameraFragment();
        cameraFragment.getCameraAsync(this);
        getChildFragmentManager().beginTransaction()
                .replace(R.id.camera_container, cameraFragment)
                .commit();
    }

Yes I solved it. Initialize your FIREKAST here in Streamer Fragment.

**Comment by francoisrouault** [comment]
👍 
I would even suggest to call `Firekast.initialize(getContext(), "YOUR_KEY");` as soon as possible when your app starts. The best place to do that is in your Application class' `onCreate` (example [kotlin](https://github.com/Firekast-io/firekast-demo-android/blob/master/app/src/main/java/io/firekast/demo/App.kt#L15), [java](https://github.com/Firekast-io/firekast-demo-android/blob/master/appjava/src/main/java/io/firekast/appjava/App.java#L16)). 

PS: do not forget to "register" this class in your `AndroidManifest` so Android knows (see [example](https://github.com/Firekast-io/firekast-demo-android/blob/master/app/src/main/AndroidManifest.xml#L10)).

**Comment by Yesha052** [comment]
Thanks, guys. Above issue is resolved. But I am getting below in stream value. The live video is not started. Only getting the "waiting" state. 
 **mStreamer.startStreaming(**stream**, StreamerFragment.this);** 
{"id":"ljy26rv7u6tvicn8n","state":"WAITING","metadata":{},"createdAt":"Mon Jul 22 10:46:21 GMT+05:30 2019","updatedAt":"Mon Jul 22 10:46:21 GMT+05:30 2019","ingestTimeout":"Mon Jul 22 10:55:51 GMT+05:30 2019"}
