### ISSUE TITLE
RTMPS url is not working.

### ISSUE THREAD

**Issue by Yesha052** [Firekast-io/firekast-demo-android#7]
Hi, 
I want to play RTMPS URL. It is not working currently. Can anyone please help me out?

**Comment by francoisrouault** [comment]
Hi @Yesha052, 

I was able to restream on, for example, Facebook Live Video RTMPS URL. I have updated the demo app adding the capability to restream on Facebook (see. c851d18569c27c78116f64a0929548788264bdae).

I have tested with success on both Emulator API 27 and device (Motorola XT1052 API22).

Keep us informed,
Regards
